spring.application.name=personal-finance-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/finance_manager
spring.datasource.username=postgres
spring.datasource.password=Asma@0206

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true